# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PostTrio
logo: "/assets/img/logo.png"
email: contact@posttrio.com
description: > # this means to ignore newlines until "baseurl:"
  PostTrio is a digital marketing app. It makes the process of promoting yourself online simple & helps you create amazing content!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://posttrio.com/" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: posttrio
twitter_username: posttrio
linkedin_username: posttrio
instagram_username: posttrio
google_analytics: UA-176733882-1
permalink: /:categories/:title/
excerpt_separator: <!--more-->

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true